name: Download Hong Kong Vaccination Data

on:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:

jobs:
  download-vaccination-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: |
          git config user.name github-actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          ./download.sh
